% 将远场位移的P波，SV，SH的辐射图案用离源角ixi、接收点方位角phi、
% 源点——走向phis，倾角delta，滑动角lamda的函数
% 这里引入震中坐标系x,y,z，x==north，y==east，z=down
% 无限均匀各向同性介质
function [FP, FSV, FSH] = CalcFarfieldDisp(ixi, phis, delta, lamda, phi)
  % convert degree to rad
  ixi = deg2rad(ixi) ;
  phis = deg2rad(phis) ;
  delta = deg2rad(delta) ;
  lamda = deg2rad(lamda) ;
  phi = deg2rad(phi) ;
  % far-field P radiation pattern
  FP = cos(lamda)*sin(delta)*sin(ixi).^2*sin(2*(phi-phis)) ...
      - cos(lamda)*cos(delta)*sin(2*ixi)*cos(phi-phis) ...
      + sin(lamda)*sin(2*delta)*(cos(ixi).^2-sin(ixi).^2*sin(phi-phis).^2) ...
      + sin(lamda)*cos(2*delta)*sin(2*ixi)*sin(phi-phis) ;
  % far-field SV radiation pattern
  FSV = sin(lamda)*cos(2*delta)*cos(2*ixi)*sin(phi-phis) ...
      - cos(lamda)*cos(delta)*cos(2*ixi)*cos(phi-phis) ...
      + 0.5*cos(lamda)*sin(delta)*sin(2*ixi)*sin(2*(phi-phis)) ...
      - 0.5*sin(lamda)*sin(2*delta)*sin(2*ixi)*(1+sin(phi-phis).^2) ;
  % far-field SH radiation pattern
  FSH = cos(lamda)*cos(delta)*cos(ixi)*sin(phi-phis) ...
      + cos(lamda)*sin(delta)*sin(ixi)*cos(2*(phi-phis)) ...
      + sin(lamda)*cos(2*delta)*cos(ixi)*cos(phi-phis) ...
      -0.5*sin(lamda)*sin(2*delta)*sin(ixi)*sin(2*(phi-phis)) ;
  
end