function [fitresult, gof] = pgsgautofit(sg, dist, pg)
%CREATEFITS(SG,DIST,PG)
%  Create fits.
%
%  Data for 'sgfit' fit:
%      X Input : sg
%      Y Output: dist
%  Data for 'pgfit' fit:
%      X Input : pg
%      Y Output: dist
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-May-2017 16:11:53

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'sgfit'.
[xData, yData] = prepareCurveData( sg, dist );

% Set up fittype and options.
ft = fittype( 'b.*sqrt((x./a).^2-1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.00765057917816969 0.812780008887377];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'sgfit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{1}, xData, yData );
legend( h, 'dist vs. sg', 'sgfit', 'Location', 'NorthEast' );
% Label axes
xlabel sg
ylabel dist
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{1}, xData, yData, 'residuals' );
legend( h, 'sgfit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel sg
ylabel dist
grid on

%% Fit: 'pgfit'.
[xData, yData] = prepareCurveData( pg, dist );

% Set up fittype and options.
ft = fittype( 'b.*sqrt((x./a).^2-1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.688052999538227 0.229404091138869];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'pgfit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{2}, xData, yData );
legend( h, 'dist vs. pg', 'pgfit', 'Location', 'NorthEast' );
% Label axes
xlabel pg
ylabel dist
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{2}, xData, yData, 'residuals' );
legend( h, 'pgfit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel pg
ylabel dist
grid on


